Name:           perl-JQ-XS
Version:        1.01
Release:        1%{?dist}
Summary:        Perl wrapper for libjq
License:        MIT
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/JQ-XS/
Source0:        http://www.cpan.org/modules/by-module/JQ/JQ-XS-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
# Toolchain: JQ::XS is an XS module, so a compiler and the perl headers are
# needed, plus perl-generators for the automatic perl(...) dependencies and
# perl-podlators for the pod2man that produces the man page in %files.
BuildRequires:  gcc
BuildRequires:  make
BuildRequires:  findutils
BuildRequires:  perl-devel
BuildRequires:  perl-generators
BuildRequires:  perl-podlators
BuildRequires:  perl(ExtUtils::MakeMaker)
# libjq itself.
BuildRequires:  jq-devel
# Used by t/JQ-XS.t, which %check runs.
BuildRequires:  perl(Data::Dumper)
BuildRequires:  perl(JSON::PP)
BuildRequires:  perl(Test::More)
Requires:       perl(JSON::PP)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
JQ::XS provides a clean object-oriented wrapper around libjq, the C library
behind the jq command-line tool. It allows you to:

%prep
%setup -q -n JQ-XS-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE META.json README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/JQ*
%{_mandir}/man3/*

%changelog
* Tue Sep 01 2026 James Rouzier <rouzier@gmail.com> 1.01-1
- Version the Debian packages +debNuM rather than ~debNuM

* Mon Aug 31 2026 James Rouzier <rouzier@gmail.com> 1.00-1
- Specfile autogenerated by cpanspec 1.78.
