Name:           perl-JQ-XS
Version:        2.04
Release:        1%{?dist}
Summary:        Perl wrapper for libjq
# JQ::XS is MIT.  The vendored jq is compiled in and statically linked, which
# brings its own terms along: jq itself is MIT, decNumber is under the ICU
# license, and oniguruma, NetBSD's strptime and the Heimdal bits are all
# BSD-2-Clause.  See THIRD-PARTY-LICENSES.
License:        MIT AND ICU AND BSD-2-Clause
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/JQ-XS/
Source0:        http://www.cpan.org/modules/by-module/JQ/JQ-XS-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
# Toolchain: JQ::XS is an XS module, so a compiler and the perl headers are
# needed, plus perl-generators for the automatic perl(...) dependencies and
# perl-podlators for the pod2man that produces the man page in %files.
BuildRequires:  gcc
BuildRequires:  make
BuildRequires:  findutils
BuildRequires:  perl-devel
BuildRequires:  perl-generators
BuildRequires:  perl-podlators
BuildRequires:  perl(ExtUtils::MakeMaker)
# JQ::XS compiles the jq vendored in its own tarball rather than linking the
# one the distribution packages, so there is no jq-devel here -- gcc, make and
# a shell are the whole toolchain it needs.  Unpacking and verifying that
# tarball needs two modules that RHEL ships apart from perl itself.
BuildRequires:  perl(Archive::Tar)
BuildRequires:  perl(Digest::SHA)
# Used by t/JQ-XS.t, which %check runs.
BuildRequires:  perl(Data::Dumper)
BuildRequires:  perl(JSON::PP)
BuildRequires:  perl(Test::More)
Requires:       perl(JSON::PP)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
JQ::XS provides a clean object-oriented wrapper around libjq, the C library
behind the jq command-line tool. It allows you to:

%prep
%setup -q -n JQ-XS-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE META.json README THIRD-PARTY-LICENSES
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/JQ*
%{_mandir}/man3/*

%changelog
* Fri Sep 25 2026 James Rouzier <rouzier@gmail.com> 2.04-1
- No change to what the module computes; fixes t/JQ-XS.t on a perl built
  with -Duselongdouble or -Dusequadmath, where an NV is wider than the IEEE
  double jq holds numbers in and the float round-trip test compared unequal:
  the test now narrows the literal to a double first

* Sun Sep 20 2026 James Rouzier <rouzier@gmail.com> 2.03-1
- No change to the module itself; fixes building against Archive::Tar 3.x,
  which refuses to unpack the vendored jq tarball because jq ships
  docs/content/manual/v1.8/manual.yml as a hard link: vendor/build-jq.pl
  now dereferences hard links itself and falls back to tar(1)

* Fri Sep 18 2026 James Rouzier <rouzier@gmail.com> 2.02-1
- Do not warn when another JSON module is loaded alongside JQ::XS:
  JSON::PP is now loaded only when nothing else has already overloaded
  JSON::PP::Boolean, so Cpanel::JSON::XS and JSON::XS keep their own
  operators and JQ::XS no longer redefines them

* Fri Sep 18 2026 James Rouzier <rouzier@gmail.com> 2.01-1
- No change to the module itself; fixes the release workflow's smoke test
  on RHEL 9 and 10, where blib.pm is packaged apart from perl itself

* Tue Sep 15 2026 James Rouzier <rouzier@gmail.com> 2.00-1
- Embed jq 1.8.2 rather than linking the libjq the distribution packages
- No longer requires libjq at build or run time
- Expose more of the libjq API: named/positional arguments, output
  formatting, halt/halt_error, the debug, stderr and input/inputs
  callbacks, jq attributes and JSON parse/print helpers
- New allow_includes option refuses filters that load modules from disk

* Tue Sep 01 2026 James Rouzier <rouzier@gmail.com> 1.01-1
- Version the Debian packages +debNuM rather than ~debNuM

* Mon Aug 31 2026 James Rouzier <rouzier@gmail.com> 1.00-1
- Specfile autogenerated by cpanspec 1.78.
